"""Which edition this process is, and what that edition calls itself.

Volksmond ships from one codebase as several editions (see buildflags.py for the
build-time switches). Two of them can end up installed side by side on the same
machine: the Microsoft Store edition and the direct-download edition from the
website. Both used to be called "Volksmond" and both wore the same blue-tile icon,
so nothing in the taskbar, the Start menu or Alt-Tab told them apart.

So the direct-download (connected) edition has its own visible identity: it is
"Volksmond Fast Track", with an inverted icon (white tile, brand-blue mark). The
Store edition, the offline edition and the macOS build keep the plain "Volksmond"
name and the original blue-tile icon, unchanged.

This module is derivation only, no new switches: the edition is already decided at
freeze time by which PyInstaller target built the bundle, and buildflags.py reads
that decision from the runtime hook the target installed. All that is added here is
the one case those flags cannot express on their own, "a frozen Windows build with
neither flag set", which is exactly the connected edition. A source run reports
"dev" (it is nobody's install), and the mac bundle reports "mac" so the Fast Track
name stays a Windows direct-download thing and the .app is untouched.

Read once at import, like buildflags, because the flags it derives from are read
once at import.
"""
import sys

from . import buildflags

CONNECTED = "connected"   # the direct download from the website: Volksmond Fast Track
STORE = "store"           # the Microsoft Store (MSIX) edition
OFFLINE = "offline"       # the airtight offline-only edition
MAC = "mac"               # the macOS .app (its own download channel)
DEV = "dev"               # running from source, not an installed edition

# The display name every edition except the connected one uses. Kept as a constant so a
# test can assert "the store edition still says exactly this" without repeating a literal.
BASE_NAME = "Volksmond"
FAST_TRACK_NAME = "Volksmond Fast Track"


def _detect():
    """The edition of the running process. See the module docstring for the ordering."""
    # The two hard-declared editions first: their runtime hooks force these flags before any
    # app code runs, and they are mutually exclusive by construction (see pyi_rth_*.py).
    if buildflags.OFFLINE_ONLY:
        return OFFLINE
    if buildflags.STORE_BUILD:
        return STORE
    # Not frozen: a source / dev run. It is not an installed edition and must not claim to be
    # one, or a dev window would be indistinguishable from an installed Fast Track window.
    if not getattr(sys, "frozen", False):
        return DEV
    # Frozen, no edition flag. On mac that is volksmond-mac.spec (which installs no runtime
    # hook); on Windows it is the connected target of sa-live-transcribe.spec.
    if sys.platform == "darwin":
        return MAC
    return CONNECTED


EDITION = _detect()

#: What this edition calls itself in the window title, the installer and the shortcuts.
DISPLAY_NAME = FAST_TRACK_NAME if EDITION == CONNECTED else BASE_NAME

#: The app / taskbar / tray icon file for this edition, as a bare filename. Both files are
#: generated by build-icon.py from the real brand mark; sa-live-transcribe.spec bundles the
#: one that matches the edition it is building, so only ever one of them is present.
ICON_FILE = "volksmond-fasttrack.ico" if EDITION == CONNECTED else "volksmond.ico"

#: The browser-tab icon for this edition, as a filename under web/static (served from /assets).
FAVICON_FILE = "favicon-fasttrack.svg" if EDITION == CONNECTED else "favicon.svg"


def brand_page(html):
    """Stamp this edition's identity onto the served index page.

    Only the connected edition changes anything: the tab title becomes "Volksmond Fast
    Track" and the tab icon becomes the inverted favicon. Every other edition gets the page
    back byte for byte, so the Store and offline UIs are untouched.
    """
    if EDITION != CONNECTED:
        return html
    html = html.replace(f"<title>{BASE_NAME}</title>", f"<title>{DISPLAY_NAME}</title>", 1)
    return html.replace("/assets/favicon.svg", f"/assets/{FAVICON_FILE}", 1)
